import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/theme";
import { ApolloClientProvider } from "@/lib/apollo-provider";
import { ToastProvider } from "@/components/ui/toast";
import { PublishedItemsProvider } from "@/context/published-items-context";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ApolloClientProvider>
          <ThemeProvider
            defaultColorName="green"
            defaultMode="black"
            defaultDirection="ltr"
            enableSystemModeDetection={false}
            enableDirectionDetection={false}
          >
            <ToastProvider>
              <PublishedItemsProvider>
                {children}
              </PublishedItemsProvider>
            </ToastProvider>
          </ThemeProvider>
        </ApolloClientProvider>
      </body>
    </html>
  );
}
